-- 002 — AI provenance for synthetic catalogue entries.
--
-- Part of the catalogue is fabricated demonstration data. Until now the only
-- signal was books.source = 'synthetic', which is not enough to disclose at the
-- UI and MCP layers. These columns carry the provenance that the disclosure is
-- rendered from, and the CHECK constraint makes an unmarked synthetic row
-- impossible to insert.

ALTER TABLE books
  ADD COLUMN IF NOT EXISTS generated_by      TEXT,
  ADD COLUMN IF NOT EXISTS generated_at      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS synthetic_notice  TEXT;

-- Backfill before adding the constraint, or the existing 25 rows would violate it.
UPDATE books
SET
  generated_by     = COALESCE(generated_by, 'claude-opus-5'),
  generated_at     = COALESCE(generated_at, NOW()),
  synthetic_notice = COALESCE(
    synthetic_notice,
    'Fabricated content generated by AI for demonstration purposes. Not a real published work.'
  )
WHERE source = 'synthetic';

ALTER TABLE books
  DROP CONSTRAINT IF EXISTS synthetic_must_be_marked;

ALTER TABLE books
  ADD CONSTRAINT synthetic_must_be_marked
  CHECK (source <> 'synthetic' OR (generated_by IS NOT NULL AND synthetic_notice IS NOT NULL));

CREATE INDEX IF NOT EXISTS books_synthetic_idx ON books(source) WHERE source = 'synthetic';
