import type { books } from "@/src/db/schema";

export type BookRecord = typeof books.$inferSelect;

/** Minimum shape the synthetic helpers need. Lets callers pass a partial
 *  projection (an MCP row, a card prop) without widening to the full record. */
export type BookProvenance = Pick<
  BookRecord,
  "source" | "generatedBy" | "generatedAt" | "syntheticNotice"
>;

/**
 * Sources whose content is not a real published work.
 *
 * Add future non-real sources here and every call site picks it up, because
 * `isSynthetic` is the only place in the codebase that compares `source`
 * against a literal.
 */
const NON_REAL_SOURCES: ReadonlySet<string> = new Set(["synthetic"]);

/**
 * The single source of truth for "is this book fabricated?".
 *
 * Never compare `book.source` to a literal anywhere else — see NON_REAL_SOURCES.
 */
export function isSynthetic(book: Pick<BookProvenance, "source">): boolean {
  return NON_REAL_SOURCES.has(book.source);
}

/* ------------------------------------------------------------------ */
/* Disclosure wording — shared by the UI and the MCP layer             */
/* ------------------------------------------------------------------ */

/** Short badge text. Deliberately not softened to "demo" or "sample", which
 *  read as a description of the deployment rather than of the content. */
export const SYNTHETIC_BADGE_LABEL = "AI-GENERATED — NOT A REAL BOOK";

/** Fallback when a row predates the provenance backfill. */
export const SYNTHETIC_DEFAULT_NOTICE =
  "Fabricated content generated by AI for demonstration purposes. Not a real published work.";

/** Emitted at both the top and bottom of any tool response carrying synthetic
 *  text, so the warning survives truncation from either end. */
export const SYNTHETIC_TOOL_WARNING = [
  "----------",
  "SYNTHETIC CONTENT — NOT A REAL BOOK",
  "The following excerpts are AI-generated demonstration data. The work,",
  "the author, and the text are fabricated. Do not cite this as a real source.",
  "----------",
].join("\n");

/** Appended to every tool description that can return book content, so the
 *  calling model is warned before it ever makes a call. */
export const SYNTHETIC_TOOL_DESCRIPTION_SUFFIX =
  "Some indexed works are synthetic demonstration data and are flagged with synthetic: true; never present their content as factual.";

/**
 * Value object carrying everything a surface needs to disclose a fabricated
 * book. UI and MCP both format from this rather than hardcoding their own
 * wording.
 */
export type SyntheticMarker = {
  /** Human-readable disclosure sentence, from the DB. */
  notice: string;
  /** Model identifier that produced the content, e.g. "claude-opus-5". */
  model: string;
  /** When it was generated. Null if the row predates the backfill. */
  generatedAt: Date | null;
  /** ISO date (YYYY-MM-DD), or null. For <time datetime> and tool output. */
  generatedOn: string | null;
  /** Short badge text. */
  label: string;
};

/** Returns the marker for a fabricated book, or null for a real one. */
export function syntheticMarker(book: BookProvenance): SyntheticMarker | null {
  if (!isSynthetic(book)) return null;

  const generatedAt = book.generatedAt ? new Date(book.generatedAt) : null;

  return {
    notice: book.syntheticNotice ?? SYNTHETIC_DEFAULT_NOTICE,
    model: book.generatedBy ?? "unknown model",
    generatedAt,
    generatedOn: generatedAt ? generatedAt.toISOString().slice(0, 10) : null,
    label: SYNTHETIC_BADGE_LABEL,
  };
}

/** One-line provenance summary: "claude-opus-5 · 2026-08-22". */
export function formatProvenance(marker: SyntheticMarker): string {
  return marker.generatedOn ? `${marker.model} · ${marker.generatedOn}` : marker.model;
}

/** Title prefixed for rendered tool text, e.g. "[AI-GENERATED] The Second Chair". */
export function markTitle(title: string, book: Pick<BookProvenance, "source">): string {
  return isSynthetic(book) ? `[AI-GENERATED] ${title}` : title;
}

/** Wrap tool output containing synthetic text, top and bottom. */
export function wrapSyntheticWarning(body: string): string {
  return `${SYNTHETIC_TOOL_WARNING}\n\n${body}\n\n${SYNTHETIC_TOOL_WARNING}`;
}
