import type { SyntheticMarker } from "@/src/core/books/entities";

/** Full disclosure callout for the book detail page. Renders the notice text,
 *  model id, and generation date carried by the marker — no wording of its own. */
export function SyntheticNotice({ marker }: { marker: SyntheticMarker }) {
  return (
    <div
      role="note"
      className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4"
    >
      <p className="text-sm font-semibold tracking-wide text-amber-300 uppercase">
        {marker.label}
      </p>

      <p className="mt-2 text-sm text-amber-100/90">{marker.notice}</p>

      <p className="mt-3 text-xs text-amber-200/70">
        Generated by <span className="font-mono">{marker.model}</span>
        {marker.generatedOn && (
          <>
            {" on "}
            <time dateTime={marker.generatedOn}>{marker.generatedOn}</time>
          </>
        )}
      </p>
    </div>
  );
}
